services:

  db:
    image: postgres:15.2
    container_name: StoreApp
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=StoreApp
      - POSTGRES_USER=jsaire
      - POSTGRES_PASSWORD=Sys$266
    ports:
      - "5432:5432"